### ISSUE TITLE
Incorrect Version Constant in v0.1.0

### ISSUE THREAD

**Issue by robotlovesyou** [getsentry/sentry-go#17]
in sentry.go you still have the version constant as 
```
const Version = "0.0.1-beta.3"
```

This then causes a warning to be shown in the UI about an out of date client SDK

**Comment by kamilogorek** [comment]
Whoops! I'll make sure to fix this with the next patch release by writing verification script. Thanks for reporting this!

**Comment by kamilogorek** [comment]
Fixed in #19

**Comment by pendolf** [comment]
It's not fixed yet, git tag v0.1.0 still had old version contrain https://github.com/getsentry/sentry-go/blob/v0.1.0/sentry.go#L9

**Comment by kamilogorek** [comment]
@pendolf @anatoliyfedorenko I had to wait for something to actually release :)

https://github.com/getsentry/sentry-go/releases/tag/v0.1.1
https://github.com/getsentry/sentry-go/blob/37a9bc03f379af10cc7a275b9d7a132225fe97f8/sentry.go#L9
